import os
import time
import threading
import urllib.parse
from typing import Optional, Dict, Any
from starlette.types import ASGIApp, Scope, Receive, Send, Message
from starlette.middleware import Middleware


class EphemeralCleanupManager:
    """
    Manages temporary/ephemeral files generated by API requests (image, video, playwright, etc.).
    Guarantees that files remain available until downloaded by the remote client,
    and are deleted promptly (with a short debounce delay) once the download completes.
    Includes a safety TTL scavenger to purge abandoned files if the client never downloads them.
    """

    def __init__(self):
        self._files: Dict[str, Dict[str, Any]] = {}
        self._lock = threading.Lock()
        self._scavenger_started = False
        self._start_scavenger()

    def _start_scavenger(self):
        if not self._scavenger_started:
            self._scavenger_started = True
            scavenger_thread = threading.Thread(target=self._scavenger_loop, daemon=True, name="EphemeralCleanupScavenger")
            scavenger_thread.start()

    def canonicalize(self, path: str) -> str:
        """Returns normalized, lowercase, absolute path for dictionary keying."""
        try:
            return os.path.normcase(os.path.abspath(str(path)))
        except Exception:
            return str(path).lower()

    def register(self, file_path: str, delay: float = 5.0, ttl: float = 3600.0) -> str:
        """
        Register a generated file to be deleted after it is downloaded by a remote client.
        :param file_path: Path to the generated file.
        :param delay: Seconds to wait after download completes before deleting (debounce for range requests).
        :param ttl: Max lifetime in seconds if never downloaded by a client (default: 1 hour).
        """
        if not file_path:
            return file_path

        abs_path = os.path.abspath(file_path)
        canonical = self.canonicalize(abs_path)

        with self._lock:
            existing = self._files.get(canonical)
            if existing and existing.get("timer"):
                try:
                    existing["timer"].cancel()
                except Exception:
                    pass

            self._files[canonical] = {
                "path": abs_path,
                "registered_at": time.time(),
                "delay": max(1.0, float(delay)),
                "ttl": max(60.0, float(ttl)),
                "timer": None,
                "download_count": 0,
            }

        print(f"[EphemeralCleanup] Registered file for post-download cleanup: {abs_path} (delay: {delay}s, ttl: {ttl}s)")
        return abs_path

    def unregister(self, file_path: str) -> bool:
        canonical = self.canonicalize(file_path)
        with self._lock:
            entry = self._files.pop(canonical, None)
            if entry and entry.get("timer"):
                try:
                    entry["timer"].cancel()
                except Exception:
                    pass
            return entry is not None

    def match_url_path(self, url_path: str) -> Optional[str]:
        """
        Extract the target file path from common Gradio / FastAPI file-serving URLs
        and check if it matches a registered ephemeral file.
        """
        if not url_path:
            return None

        unquoted = urllib.parse.unquote(url_path)
        prefixes = [
            "/gradio_api/file=",
            "/file=",
            "/gradio_api/file/",
            "/file/",
        ]

        target = None
        for prefix in prefixes:
            if unquoted.startswith(prefix):
                target = unquoted[len(prefix):]
                break

        if target is None:
            # Query string fallback: ?file=...
            if "?file=" in unquoted:
                target = unquoted.split("?file=", 1)[-1]
            elif "&file=" in unquoted:
                target = unquoted.split("&file=", 1)[-1]

        if not target:
            return None

        # Clean any trailing query parameters
        target = target.split("?")[0].replace("\\", "/")
        canonical = self.canonicalize(target)

        with self._lock:
            if canonical in self._files:
                return canonical

        return None

    def mark_downloaded(self, canonical_path: str):
        """
        Called when a client completes downloading the file.
        Debounces file deletion to allow potential secondary range requests to finish,
        then permanently removes the file from disk.
        """
        with self._lock:
            entry = self._files.get(canonical_path)
            if not entry:
                return

            entry["download_count"] = entry.get("download_count", 0) + 1
            if entry.get("timer"):
                try:
                    entry["timer"].cancel()
                except Exception:
                    pass

            target_path = entry["path"]
            delay = entry.get("delay", 5.0)

            def _delete_worker():
                self._delete_file_with_retry(target_path, canonical_path)

            timer = threading.Timer(delay, _delete_worker)
            entry["timer"] = timer
            timer.daemon = True
            timer.start()

        print(f"[EphemeralCleanup] Download completed for '{target_path}'. Scheduled deletion in {delay}s.")

    def _delete_file_with_retry(self, target_path: str, canonical_path: str, max_retries: int = 4):
        """Removes the file with exponential backoff retries in case Windows briefly locks it."""
        try:
            for attempt in range(max_retries):
                try:
                    if os.path.exists(target_path):
                        os.remove(target_path)
                        print(f"[EphemeralCleanup] Cleaned up downloaded file: {target_path}")
                    break
                except PermissionError:
                    if attempt < max_retries - 1:
                        time.sleep(0.5 * (2 ** attempt))
                    else:
                        print(f"[EphemeralCleanup] Warning: Could not delete locked file after retries: {target_path}")
                except Exception as e:
                    print(f"[EphemeralCleanup] Error deleting file {target_path}: {e}")
                    break
        finally:
            with self._lock:
                self._files.pop(canonical_path, None)

    def manual_delete(self, file_path: str) -> bool:
        """Immediately delete a registered file."""
        canonical = self.canonicalize(file_path)
        with self._lock:
            entry = self._files.pop(canonical, None)
            if entry and entry.get("timer"):
                try:
                    entry["timer"].cancel()
                except Exception:
                    pass

        target_path = entry["path"] if entry else os.path.abspath(file_path)
        try:
            if os.path.exists(target_path):
                os.remove(target_path)
                print(f"[EphemeralCleanup] Manually deleted: {target_path}")
                return True
        except Exception as e:
            print(f"[EphemeralCleanup] Error in manual_delete {target_path}: {e}")
        return False

    def _scavenger_loop(self):
        """Periodically scans for expired un-downloaded files to prevent disk leaks."""
        while True:
            try:
                time.sleep(60)
                now = time.time()
                expired = []
                with self._lock:
                    for canon, entry in list(self._files.items()):
                        # Only delete if TTL expired and no active download debounce timer is running
                        if (now - entry["registered_at"] > entry["ttl"]) and (entry.get("timer") is None):
                            expired.append((canon, entry["path"]))
                            self._files.pop(canon, None)

                for canon, path in expired:
                    try:
                        if os.path.exists(path):
                            os.remove(path)
                            print(f"[EphemeralCleanup] Cleaned up abandoned file after TTL ({path})")
                    except Exception as e:
                        print(f"[EphemeralCleanup] Scavenger error for {path}: {e}")
            except Exception as e:
                print(f"[EphemeralCleanup] Scavenger loop exception: {e}")


class EphemeralCleanupMiddleware:
    """
    ASGI Middleware that monitors file-serving routes.
    When a registered ephemeral file finishes streaming to the client with HTTP 200 or 206,
    it triggers post-download cleanup.
    """

    def __init__(self, app: ASGIApp):
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send):
        if scope.get("type") != "http":
            await self.app(scope, receive, send)
            return

        method = scope.get("method", "GET").upper()
        # Only cleanup on GET requests (HEAD requests are metadata probes)
        if method != "GET":
            await self.app(scope, receive, send)
            return

        url_path = scope.get("path", "")
        canonical_target = ephemeral_manager.match_url_path(url_path)

        if not canonical_target:
            # Check raw query string if path didn't match
            query_string = scope.get("query_string", b"").decode("utf-8", errors="ignore")
            if query_string:
                canonical_target = ephemeral_manager.match_url_path(f"{url_path}?{query_string}")

        if not canonical_target:
            await self.app(scope, receive, send)
            return

        # Track transfer completion and response status
        response_status = [200]
        body_completed = [False]

        async def send_interceptor(message: Message):
            msg_type = message.get("type")
            if msg_type == "http.response.start":
                response_status[0] = message.get("status", 200)
            elif msg_type == "http.response.body" and not message.get("more_body", False):
                body_completed[0] = True
            await send(message)

        try:
            await self.app(scope, receive, send_interceptor)
        finally:
            if body_completed[0] and response_status[0] in (200, 206):
                ephemeral_manager.mark_downloaded(canonical_target)


# Global singleton instance
ephemeral_manager = EphemeralCleanupManager()
register_ephemeral_file = ephemeral_manager.register
